### ISSUE TITLE
Struggling to get FoscamAPI running

### ISSUE THREAD

**Issue by Oscar-T24** [hypothermic/FoscamAPI#5]
Hello, 
I am a true newbie in java and I can't get FoscamAPI to work on my computer.

After installing the latest java update and running the latest release of foscamAPI in my command prompt, I get the following error : ` java.lang.ClassNotFoundException: jar` (my command was  : `java jar foscamlib-1.08-RELEASE.jar`)

Any help would be greatly appreciated

**Comment by hypothermic** [comment]
Hello,

It looks like you're trying to run FoscamAPI as an executable program. However, this is not possible as it is only a **library**. You will have to create your own application that integrates the library and calls it's functions.

An example application is the [FoscamViewer](https://github.com/hypothermic/FoscamViewer) desktop app. You can download it on the Github page and run it with `java -jar fscviewer-1.17-xxxxx-64bit.jar` (note the dash before the word 'jar'!)

I would try to run FoscamViewer first to make sure it works with your camera :)

**Comment by Oscar-T24** [comment]
I first came across FoscamAPI when I searched for an alternative to the cloud based foscam application, and I didn't know about FoscamViewer !! After downloading the macOS version `fscviewer-1.17-osx.jar`, and running the java -jar commannd, I get an (quite long) error message that I can't decipher at all (maybe it has to do with the runtime evironment?)
`Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:904)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.MissingResourceException: Can't find bundle for base name locale.i18n, locale fr_FR
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at nl.hypothermic.fscviewer.FoscamViewer.start(FoscamViewer.java:44)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application nl.hypothermic.fscviewer.FoscamViewer`
Thank you !

**Comment by hypothermic** [comment]
Hi @Oscar-T24 , thanks for sharing the error,

Please understand this is quite an old application (dating back to 2018) and it has some flaws. I don't think I've ever tested it on OSX, even though there is a binary for it 😅 

Could you try to launch it the following way?:
```shell
java -Duser.country=EN -Duser.language=en -jar ./fscviewer-1.17-osx.jar "lang=en_EN"
```

The error is caused by the app not supporting your system locale (fr_FR), and I hope that the arguments above will change the app locale to en_EN, which is supported.

**Comment by Oscar-T24** [comment]
Yes ! It did work fine this time. 

However as I connect to my camera there is no output display coming out. I could test the controls in a separate vlc window with the rstp stream and they do work — but once I click on a direction it wouln't stop the camera from moving once released (until eventually the camera has fully revolved).

 I'd be very interested in knowing how you implemented the ptz controls in java though (would it be possible in python ?)

I noticed another error (the only one error now) which might prevent the video from loading. Here is the traceback : 
`Exception in thread "FSCV-UI" java.lang.NullPointerException
	at nl.hypothermic.fscviewer.ui.InterfaceController$5.changed(InterfaceController.java:127)
	at nl.hypothermic.fscviewer.ui.InterfaceController$5.changed(InterfaceController.java:125)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1324)
	at javafx.scene.control.TextInputControl.setText(TextInputControl.java:349)
	at nl.hypothermic.fscviewer.ui.InterfaceController.initialize(InterfaceController.java:177)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2553)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2446)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2414)
	at nl.hypothermic.fscviewer.FoscamViewer.start(FoscamViewer.java:51)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)`

Speaking of UI, I find it very clean ;))
Thank you for all your help so far !!

**Comment by hypothermic** [comment]
Hi @Oscar-T24 ,

I don't own a Foscam camera anymore, hence the programs haven't been updated in some time and I won't be able to test new releases.
Probably the reason why the PTZ movement doesn't stop is because the program doesn't call the `ptzStopMoving` function upon release of the button.
The code for this app is such a mess... maybe I can borrow a friend's camera and rework the code sometime.

> I'd be very interested in knowing how you implemented the ptz controls in java though (would it be possible in python ?)

Basically, you send a HTTP GET request to the camera and put the action in the URL, like:
```
http://192.168.1.100:88/cgi-bin/CGIProxy.fcgi?usr=Username&pwd=Password&cmd=ptzMoveRight
```
Make sure that the username and password are URL-encoded (no symbols).

I don't use Python much, but something like this should work:
```python
from urllib.parse import urlencode
from urllib.request import urlopen
from time import sleep

address = '192.168.1.100'
port = 88
username = 'admin'
password = 'admin'

def exec_cmd(command):
    params = urlencode(dict(usr=username,pwd=password,cmd=command))
    url = f'http://{address}:{port}/cgi-bin/CGIProxy.fcgi?{params}'
    urlopen(url) # todo: check return xml

# all available commands are found here:
# https://www.foscam.es/descarga/Foscam-IPCamera-CGI-User-Guide-AllPlatforms-2015.11.06.pdf#page=47&zoom=auto,-312,843

exec_cmd('ptzMoveRight')
sleep(2)
exec_cmd('ptzStopRun')
sleep(2)
exec_cmd('ptzReset')
sleep(2)
exec_cmd('ptzMoveLeft')
```
Let me know if you get it working 😄

**Comment by Oscar-T24** [comment]
Hello back @hypothermic  !

After a week of hard work (kind of) I successfully made a python based executable to control my foscam camera remotely !!

My app uses pygame to display the rstp feed, and your very nice `exec_cmd()` function to handle HTTP requests.

I created a repo dedicated to it, which I kept private for now (but I can share it with anyone who is interested)

Thanks for everything !

**Comment by hypothermic** [comment]
I'm glad you got it working @Oscar-T24 ! 🥳
